# No less than 1min as its the timer frequency
/var/srv/bofzilla/containers/*			15min
/var/srv/bofzilla/containers/lldap		15min
/var/srv/bofzilla/containers/authelia	6h
/var/srv/bofzilla/containers/caddy		1d
/var/srv/bofzilla/containers/crowdsec	1w
/var/srv/bofzilla/containers/gatus		1d
# Needs a line after latest path