## General config
SSH_PORT: {{ gopass "telstar/ssh-port" }}
PODMAN_TUNNEL_SUBNET: 10.89.0.0/26

## Domain configuration
DOMAIN:
  URL: bofzilla.dev
  SSL: true
  CLOUDFLARE_API_TOKEN: {{ gopass "--password" "domains/bofzilla.dev/api-key.caddy.cloudflare" }}

## Backup strategy
BACKUP:
  ENABLED: true
  STORAGEBOX_USER: {{ gopass "backups/backupiter/telstar.account" "user" }}
  STORAGEBOX_PASS: {{ gopass "--password" "backups/backupiter/telstar.account" }}

## Crowdsec conf
CROWDSEC:
  ENROLL_KEY: {{ gopass "api-key.crowdsec" }}
  INSTANCE_NAME: telstar
  CADDY_BOUNCER_API_KEY: {{ random.AlphaNum 80 }}
  FIREWALL_BOUNCER_API_KEY: {{ random.AlphaNum 80 }}

## Auth
LLDAP:
  SUBDOMAIN: lldap.auth
  ADMIN_USER: {{ gopass "telstar/lldap-admin" "user" }}
  ADMIN_PASS: {{ gopass "--password" "telstar/lldap-admin" }}
  KEY_SEED: {{ gopass "telstar/lldap-key-seed" }}
  JWT_SECRET: {{ random.AlphaNum 120 }}