---
# .ansible-lint

profile: production
strict: true

enable_list:
  - empty-string-compare # opt-in
  - galaxy-version-incorrect # opt-in
  - loop-var-prefix # opt-in
  - name[prefix] # opt-in
  - no-log-password # opt-in
  - no-prompting # opt-in
  - no-same-owner # opt-in
      # - only-builtins # opt-in <https://github.com/ansible/ansible-lint/issues/2904>

exclude_paths:
  - .ansible
  - .editorconfig
  - .config
  - .github
  - .gitignore
  - .password-store
  - .shellcheckrc
  - "*.json"
  - "*.cfg"
  - "*.toml"
