## Will still need
# pip install -r .config/requirements.txt
# ansible-galaxy install --force -r .config/requirements.yml
[env]
_.python.venv = { path = "{{ config_root }}/.venv", create = true }
ANSIBLE_HOME="{{ config_root }}/.ansible"
GOPASS_HOMEDIR="{{ config_root }}"

[tools]
actionlint = "1.7.11"
bat = "0.26.1"
butane = "0.25.0"
dive = "0.13.1"
dockle = "0.4.15"
gomplate = "5.0.0"
gopass = "1.16.1"
grype = "0.108.0"
hcloud = "1.61.0"
hcloud-upload-image = "1.3.0"
jq = "1.8.1"
just = "1.46.0"
python = "3.14.3"
ripgrep = "15.1.0"
rust-script = "0.36.0" # Temporary, requires cargo
shellcheck = "0.11.0"
shfmt = "3.12.0"
typos = "1.43.5"
zizmor = "1.22.0"

[alias]
butane = "asdf:Okeanos/asdf-butane"
gomplate = "asdf:tapih/asdf-gomplate"
hcloud-upload-image = "asdf:vic1707/asdf-hcloud-upload-image"
zizmor = "asdf:vic1707/asdf-zizmor"
rust-script = "asdf:vic1707/asdf-rust-script"

[settings.python]
compile = false ## Forces download of precompiled bin
