[env]
_.python.venv = { path = "{{ config_root }}/.venv", create = true }
ANSIBLE_HOME="{{ config_root }}/.ansible"
GOPASS_HOMEDIR="{{ config_root }}"

[hooks]
postinstall = "pip install -r {{ config_root }}/.config/requirements.txt && ansible-galaxy install --force -r .config/requirements.yml"

[tools]
actionlint = "1.7.7"
bat = "0.25.0"
butane = "0.24.0"
gomplate = "4.3.3"
gopass = "1.15.16"
hcloud = "1.51.0"
hcloud-upload-image = "1.1.0"
jq = "1.8.1"
just = "1.42.4"
python = "3.13.6"
ripgrep = "14.1.1"
shellcheck = "0.11.0"
shfmt = "3.12.0"
typos = "1.35.3"
zizmor = "1.5.2" # https://github.com/cargo-bins/cargo-quickinstall/issues/367

[alias]
butane = "asdf:Okeanos/asdf-butane"
gomplate = "asdf:tapih/asdf-gomplate"
hcloud-upload-image = "asdf:vic1707/asdf-hcloud-upload-image"
zizmor = "asdf:vic1707/asdf-any-cargo-quickinstall"

[settings]
experimental = true ## Enables hooks

[settings.python]
compile = false ## Forces download of precompiled bin
