[env]
ANSIBLE_HOME="{{ config_root }}/.ansible"
GOPASS_HOMEDIR="{{ config_root }}"

[tools]
actionlint = "1.7.7"
ansible = "11.4.0"
ansible-lint = "25.2.1"
pipx = "1.7.1" ## For installing ansible
ripgrep = "14.1.1"
shellcheck = "0.10.0"
shfmt = "3.11.0"
typos-cli = "1.31.1"
zizmor = "1.5.2"

[alias]
ansible-lint = "pipx:ansible-lint"
ripgrep = "asdf:vic1707/asdf-any-cargo-quickinstall"
typos-cli = "asdf:vic1707/asdf-any-cargo-quickinstall"
zizmor = "asdf:vic1707/asdf-any-cargo-quickinstall"
