# TODO: fix volumes z options

networks:
    shared:
        name: shared
        driver: bridge
        ipam:
            config:
                - subnet: 10.99.0.0/26

secrets:
    ## GICKUP
    gickup_vic1707_github_token:
        external: true
    ## Gluetun
    wireguard_private_key:
        external: true
    wireguard_addresses:
        external: true
    wireguard_preshared_key:
        external: true
    ## AUTHELIA
    authelia_storage_encryption_key:
        external: true
    authelia_jwt_secret:
        external: true
    authelia_smtp_password:
        external: true

############# GLOBAL VARIABLES ##############
x-TIMEZONE: &TIMEZONE Europe/Paris
##
x-AUTHELIA: &AUTHELIA docker.io/authelia/authelia:4.38.16
x-AUTHELIA_IP: &AUTHELIA_IP 10.99.0.2
##
x-CADDY: &CADDY docker.io/library/caddy:2.8.4-alpine
x-CADDY_IP: &CADDY_IP 10.99.0.3
##
x-GICKUP: &GICKUP docker.io/buddyspencer/gickup:0.10.36
x-GICKUP_IP: &GICKUP_IP 10.99.0.4
##
x-JELLYFIN: &JELLYFIN docker.io/jellyfin/jellyfin:10.9.11
x-JELLYFIN_IP: &JELLYFIN_IP 10.99.0.5
##
x-WIREGUARD: &WIREGUARD ghcr.io/wg-easy/wg-easy:14
x-WIREGUARD_IP: &WIREGUARD_IP 10.99.0.61
##
x-GLUETUN: &GLUETUN docker.io/qmcgaw/gluetun:v3.39.1
x-GLUETUN_IP: &GLUETUN_IP 10.99.0.62
##
x-TRANSMISSION: &TRANSMISSION docker.io/linuxserver/transmission:4.0.6
########### GLOBAL CONFIGURATIONS ###########
x-ips: &container-ips
    AUTHELIA_IP: *AUTHELIA_IP
    CADDY_IP: *CADDY_IP
    GICKUP_IP: *GICKUP_IP
    JELLYFIN_IP: *JELLYFIN_IP
    GLUETUN_IP: *GLUETUN_IP
    WIREGUARD_IP: *WIREGUARD_IP

x-vpn: &VPN
    network_mode: service:gluetun
    depends_on:
        - gluetun

x-common-settings: &common-settings
    sysctls:
        net.ipv6.conf.all.disable_ipv6: 1
    security_opt:
        - &no-privilege no-new-privileges=true
    restart: always
    environment: &common-env
        TZ: *TIMEZONE
#############################################

services:
    ##############################
    ######    Authelia      ######
    ##############################
    authelia:
        container_name: authelia
        <<: *common-settings
        image: *AUTHELIA
        networks:
            shared:
                ipv4_address: *AUTHELIA_IP
        secrets:
            - authelia_storage_encryption_key
            - authelia_jwt_secret
            - authelia_smtp_password
        environment:
            <<: *common-env
            X_AUTHELIA_CONFIG_FILTERS: template # Allows env var interpolation
            AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/authelia_storage_encryption_key
            AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /run/secrets/authelia_jwt_secret
            AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /run/secrets/authelia_smtp_password
            ##############
            ##   .env   ##
            ##############
            DOMAIN: ${DOMAIN}
        volumes:
            - /mnt/config/authelia:/config:z,rw

    ##############################
    ######     Gluetun      ######
    ##############################
    gluetun:
        container_name: gluetun
        # see https://github.com/qdm12/gluetun-wiki/blob/main/errors/tun.md#tun-device-is-not-available-open-devnettun-permission-denied
        privileged: true
        <<: *common-settings
        image: *GLUETUN
        networks:
            shared:
                ipv4_address: *GLUETUN_IP
        cap_add:
            - NET_ADMIN
        environment:
            <<: *common-env
            VPN_TYPE: wireguard
            VPN_SERVICE_PROVIDER: windscribe
        secrets:
            - wireguard_private_key
            - wireguard_addresses
            - wireguard_preshared_key

    ##############################
    ######      Caddy       ######
    ##############################
    caddy:
        container_name: caddy
        <<: *common-settings
        image: *CADDY
        networks:
            shared:
                ipv4_address: *CADDY_IP
        ports:
            - 8080:80
            - 4443:443
        environment:
            <<: [*common-env, *container-ips]
            ##############
            ##   .env   ##
            ##############
            DOMAIN: ${DOMAIN}
            ZEROSSL_EMAIL: ${ZEROSSL_EMAIL}
        volumes:
            - /mnt/config/caddy/Caddyfile:/etc/caddy/Caddyfile:z,ro
            - /mnt/config/caddy:/data/caddy:z,rw

    ##############################
    ######      Gickup      ######
    ##############################
    gickup:
        container_name: gickup
        <<: *common-settings
        image: *GICKUP
        networks:
            shared:
                ipv4_address: *GICKUP_IP
        volumes:
            - /mnt/bhulk/gickup:/data:rw
            - /mnt/config/gickup/conf.yml:/gickup/conf.yml:z,ro
        secrets:
            - gickup_vic1707_github_token

    ##############################
    ######     Jellyfin     ######
    ##############################
    jellyfin:
        container_name: jellyfin
        <<: *common-settings
        image: *JELLYFIN
        security_opt:
            - *no-privilege
            - label=disable
        networks:
            shared:
                ipv4_address: *JELLYFIN_IP
        environment:
            <<: *common-env
            # https://ffmpeg.org/ffmpeg-formats.html
            # probesize: 500000000 Bytes = 500 MB
            # analyzeduration: 60000000 Microseconds = 1 minute
            JELLYFIN_FFmpeg__probesize: 500000000
            JELLYFIN_FFmpeg__analyzeduration: 60000000
        volumes:
            - /mnt/config/jellyfin:/config:rw
            - /media/jellyfin:/media:ro
        devices:
            nvidia.com/gpu: all

    ##############################
    ######   Transmission   ######
    ##############################
    transmission:
        container_name: transmission
        <<: [*common-settings, *VPN]
        image: *TRANSMISSION
        environment:
            <<: *common-env
            # TODO: I HATE THIS, these are the IDs from vic1707 on bhulk
            PGID: 3000
            PUID: 3000
            DOCKER_MODS: linuxserver/mods:transmission-floodui|linuxserver/mods:transmission-env-var-settings
            TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED: true
            TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME: /config/keep_torrent_file.sh
        volumes:
            - /mnt/bhulk/transmission:/downloads:rw
            - /mnt/config/transmission:/config:z,rw
            - /mnt/config/transmission/keep_torrent_file.sh:/config/keep_torrent_file.sh:z

    ##############################
    ######    Wireguard     ######
    ##############################
    wireguard:
        container_name: wireguard
        <<: *common-settings
        image: *WIREGUARD
        networks:
            shared:
                ipv4_address: *WIREGUARD_IP
        cap_add:
            - NET_ADMIN
            - NET_RAW
            - SYS_MODULE
        cap_drop:
            - MKNOD
            - AUDIT_WRITE
        environment:
            <<: *common-env
            WG_HOST: vpn.${DOMAIN}
            PASSWORD_HASH: ${WGUI_PASSWORD_HASH}
            WEBUI_HOST: *WIREGUARD_IP
            UI_TRAFFIC_STATS: true
            UI_ENABLE_SORT_CLIENTS: true
            UI_SHOW_LINKS: true
            UI_CHART_TYPE: 1
        volumes:
            - /mnt/config/wireguard:/etc/wireguard:z,rw
        ports:
            - 51820:51820/udp
        sysctls:
            net.ipv4.conf.all.src_valid_mark: 1
            net.ipv4.ip_forward: 1
            net.ipv6.conf.all.disable_ipv6: 1
