%YAML 1.1
---
# TODO: fix volumes z options

networks:
    shared:
        name: shared
        driver: bridge
        ipam:
            config:
                - subnet: 10.99.0.0/26

secrets:
    ## TRANSMISSION
    openvpn_creds:
        file: "$PWD/secrets/transmission-ovpn-credentials"
    ## GICKUP
    gickup_vic1707_github_token:
        external: true
    ## AUTHELIA
    authelia_storage_encryption_key:
        external: true
    authelia_jwt_secret:
        external: true
    authelia_smtp_password:
        external: true
    ## HOMEPAGE
    homepage_truenas_api_key:
        external: true
    homepage_jellyfin_api_key:
        external: true
    homepage_wgeasy_password:
        external: true

############# GLOBAL VARIABLES ##############
x-TIMEZONE: &TIMEZONE Europe/Paris
##
x-AUTHELIA: &AUTHELIA
    image: docker.io/authelia/authelia:4.38.18
x-AUTHELIA_IP: &AUTHELIA_IP 10.99.0.2
##
x-CADDY: &CADDY
    image: docker.io/library/caddy:2.9.1-alpine
x-CADDY_IP: &CADDY_IP 10.99.0.3
##
x-GICKUP: &GICKUP
    image: docker.io/buddyspencer/gickup:0.10.36
x-GICKUP_IP: &GICKUP_IP 10.99.0.4
##
x-JELLYFIN: &JELLYFIN
    image: docker.io/jellyfin/jellyfin:10.10.5
x-JELLYFIN_IP: &JELLYFIN_IP 10.99.0.5
##
x-HOMEPAGE: &HOMEPAGE
    image: ghcr.io/gethomepage/homepage:v0.10.9
x-HOMEPAGE_IP: &HOMEPAGE_IP 10.99.0.7
##
x-TRANSMISSION: &TRANSMISSION
    image: docker.io/haugene/transmission-openvpn:5.3.1
x-TRANSMISSION_IP: &TRANSMISSION_IP 10.99.0.6
##
x-WIREGUARD: &WIREGUARD
    image: ghcr.io/wg-easy/wg-easy:14
x-WIREGUARD_IP: &WIREGUARD_IP 10.99.0.61
########### GLOBAL CONFIGURATIONS ###########
x-ips: &container-ips
    AUTHELIA_IP: *AUTHELIA_IP
    CADDY_IP: *CADDY_IP
    GICKUP_IP: *GICKUP_IP
    JELLYFIN_IP: *JELLYFIN_IP
    HOMEPAGE_IP: *HOMEPAGE_IP
    TRANSMISSION_IP: *TRANSMISSION_IP
    WIREGUARD_IP: *WIREGUARD_IP

x-common-settings: &common-settings
    sysctls:
        net.ipv6.conf.all.disable_ipv6: 1
    security_opt:
        - &no-privilege no-new-privileges=true
    cap_drop:
        - ALL
    restart: always
    read_only: true
    environment: &common-env
        TZ: *TIMEZONE
#############################################

services:
    ##############################
    ######    Authelia      ######
    ##############################
    ## For readonly
    # Container accesses:
    # - /app/.healthcheck.env
    # others ?
    authelia:
        container_name: authelia
        <<: [*common-settings, *AUTHELIA]
        cap_add:
            - SETGID # su-exec: setgroups(0): Operation not permitted
        networks:
            shared:
                ipv4_address: *AUTHELIA_IP
        read_only: false
        secrets:
            - authelia_storage_encryption_key
            - authelia_jwt_secret
            - authelia_smtp_password
        environment:
            <<: *common-env
            X_AUTHELIA_CONFIG_FILTERS: template # Allows env var interpolation
            AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/authelia_storage_encryption_key
            AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /run/secrets/authelia_jwt_secret
            AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /run/secrets/authelia_smtp_password
            ##############
            ##   .env   ##
            ##############
            DOMAIN: ${DOMAIN}
        volumes:
            - $PWD/authelia/configuration.yml:/config/configuration.yml:Z,ro
            - $PWD/authelia/users_database.yml:/config/users_database.yml:Z,rw
            # Doesn't like NFS storage I think
            - /mnt/config/authelia:/data:Z,rw

    ##############################
    ######      Caddy       ######
    ##############################
    caddy:
        container_name: caddy
        <<: [*common-settings, *CADDY]
        cap_add:
            - NET_BIND_SERVICE # exec container process `/usr/bin/caddy`: Operation not permitted
        networks:
            shared:
                ipv4_address: *CADDY_IP
        ports:
            - 8080:80
            - 4443:443
        environment:
            <<: [*common-env, *container-ips]
            ##############
            ##   .env   ##
            ##############
            DOMAIN: ${DOMAIN}
            ZEROSSL_EMAIL: ${ZEROSSL_EMAIL}
        volumes:
            - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile:Z,ro
            - /mnt/config/caddy:/data/caddy:Z,rw

    ##############################
    ######     Homepage     ######
    ##############################
    ## For readonly
    # Container accesses:
    # - /app/.next/server/pages/ # next render pages cache
    homepage:
        container_name: homepage
        <<: [*common-settings, *HOMEPAGE]
        networks:
            shared:
                ipv4_address: *HOMEPAGE_IP
        read_only: false
        environment:
            <<: *common-env
            ## IPs & addresses
            HOMEPAGE_VAR_BHULK_IP: 10.0.0.2
            HOMEPAGE_VAR_CADDY_IP: *CADDY_IP
            HOMEPAGE_VAR_JELLYFIN_IP: *JELLYFIN_IP
            HOMEPAGE_VAR_TRANSMISSION_IP: *TRANSMISSION_IP
            HOMEPAGE_VAR_WIREGUARD_IP: *WIREGUARD_IP
            ## Secrets
            HOMEPAGE_FILE_TRUENAS_API_KEY: /run/secrets/homepage_truenas_api_key
            HOMEPAGE_FILE_JELLYFIN_API_KEY: /run/secrets/homepage_jellyfin_api_key
            HOMEPAGE_FILE_WIREGUARD_PASSWORD: /run/secrets/homepage_wgeasy_password
        secrets:
            - homepage_truenas_api_key
            - homepage_jellyfin_api_key
            - homepage_wgeasy_password
        volumes:
            - $PWD/homepage/bookmarks.yaml:/app/config/bookmarks.yaml:Z,ro
            - $PWD/homepage/services.yaml:/app/config/services.yaml:Z,ro
            - $PWD/homepage/settings.yaml:/app/config/settings.yaml:Z,ro
            - $PWD/homepage/widgets.yaml:/app/config/widgets.yaml:Z,ro

    ##############################
    ######      Gickup      ######
    ##############################
    gickup:
        container_name: gickup
        <<: [*common-settings, *GICKUP]
        networks:
            shared:
                ipv4_address: *GICKUP_IP
        volumes:
            - /mnt/bhulk/gickup:/data:rw
            - $PWD/gickup/conf.yml:/gickup/conf.yml:Z,ro
        secrets:
            - gickup_vic1707_github_token

    ##############################
    ######     Jellyfin     ######
    ##############################
    ## For readonly
    # - error executing hook `/usr/bin/nvidia-cdi-hook` (exit code: 1)
    jellyfin:
        container_name: jellyfin
        <<: [*common-settings, *JELLYFIN]
        networks:
            shared:
                ipv4_address: *JELLYFIN_IP
        read_only: false
        environment:
            <<: *common-env
            # https://ffmpeg.org/ffmpeg-formats.html
            # probesize: 500000000 Bytes = 500 MB
            # analyzeduration: 60000000 Microseconds = 1 minute
            JELLYFIN_FFmpeg__probesize: 500000000
            JELLYFIN_FFmpeg__analyzeduration: 60000000
        volumes:
            - /mnt/config/jellyfin:/config:rw
            - /media/jellyfin:/media:ro
        devices:
            - nvidia.com/gpu=all

    ##############################
    ######   Transmission   ######
    ##############################
    transmission:
        container_name: transmission
        <<: [*common-settings, *TRANSMISSION]
        privileged: true #  needed to acces /dev/net/tun
        read_only: false
        networks:
            shared:
                ipv4_address: *TRANSMISSION_IP
        environment:
            <<: *common-env
            GLOBAL_APPLY_PERMISSIONS: false
            OPENVPN_CONFIG: netherlands
            OPENVPN_PROVIDER: PIA
            OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
            TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED: true
            TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME: /config/transmission-home/keep_torrent_file.sh
            TRANSMISSION_WEB_UI: flood-for-transmission
            WEBPROXY_ENABLED: false
            ## Wish I could remove ##
            CREATE_TUN_DEVICE: false
            DISABLE_PORT_UPDATER: true
        secrets:
            - openvpn_creds
        volumes:
            - /mnt/bhulk/transmission:/data:rw
            - /mnt/config/transmission:/config/transmission-home:Z,rw
            - $PWD/transmission/keep_torrent_file.sh:/config/transmission-home/keep_torrent_file.sh:Z
        devices: # wish I could remove
            - /dev/net/tun

    ##############################
    ######    Wireguard     ######
    ##############################
    wireguard:
        container_name: wireguard
        <<: [*common-settings, *WIREGUARD]
        networks:
            shared:
                ipv4_address: *WIREGUARD_IP
        cap_add:
            - NET_ADMIN
            - NET_RAW
            - SYS_MODULE
        environment:
            <<: *common-env
            WG_HOST: vpn.${DOMAIN}
            PASSWORD_HASH: ${WGUI_PASSWORD_HASH}
            WEBUI_HOST: *WIREGUARD_IP
            UI_TRAFFIC_STATS: true
            UI_ENABLE_SORT_CLIENTS: true
            UI_SHOW_LINKS: true
            UI_CHART_TYPE: 1
        volumes:
            - /mnt/config/wireguard:/etc/wireguard:Z,rw
        ports:
            - 51820:51820/udp
        sysctls:
            net.ipv4.conf.all.src_valid_mark: 1
            net.ipv4.ip_forward: 1
            net.ipv6.conf.all.disable_ipv6: 1
