# TODO: fix volumes z options

networks:
    shared:
        name: shared
        driver: bridge
        ipam:
            config:
                - subnet: 10.99.0.0/26

secrets:
    ## TRANSMISSION
    openvpn_creds:
        file: "$PWD/secrets/transmission-ovpn-credentials"
    ## GICKUP
    gickup_vic1707_github_token:
        external: true
    ## AUTHELIA
    authelia_storage_encryption_key:
        external: true
    authelia_jwt_secret:
        external: true
    authelia_smtp_password:
        external: true

############# GLOBAL VARIABLES ##############
x-TIMEZONE: &TIMEZONE Europe/Paris
##
x-AUTHELIA: &AUTHELIA docker.io/authelia/authelia:4.38.16
x-AUTHELIA_IP: &AUTHELIA_IP 10.99.0.2
##
x-CADDY: &CADDY docker.io/library/caddy:2.8.4-alpine
x-CADDY_IP: &CADDY_IP 10.99.0.3
##
x-GICKUP: &GICKUP docker.io/buddyspencer/gickup:0.10.36
x-GICKUP_IP: &GICKUP_IP 10.99.0.4
##
x-JELLYFIN: &JELLYFIN docker.io/jellyfin/jellyfin:10.9.11
x-JELLYFIN_IP: &JELLYFIN_IP 10.99.0.5
##
x-TRANSMISSION: &TRANSMISSION docker.io/haugene/transmission-openvpn:5.3.1
x-TRANSMISSION_IP: &TRANSMISSION_IP 10.99.0.6
##
x-WIREGUARD: &WIREGUARD ghcr.io/wg-easy/wg-easy:14
x-WIREGUARD_IP: &WIREGUARD_IP 10.99.0.61
########### GLOBAL CONFIGURATIONS ###########
x-ips: &container-ips
    AUTHELIA_IP: *AUTHELIA_IP
    CADDY_IP: *CADDY_IP
    GICKUP_IP: *GICKUP_IP
    JELLYFIN_IP: *JELLYFIN_IP
    TRANSMISSION_IP: *TRANSMISSION_IP
    WIREGUARD_IP: *WIREGUARD_IP

x-common-settings: &common-settings
    sysctls:
        net.ipv6.conf.all.disable_ipv6: 1
    security_opt:
        - &no-privilege no-new-privileges=true
    restart: always
    environment: &common-env
        TZ: *TIMEZONE
#############################################

services:
    ##############################
    ######    Authelia      ######
    ##############################
    authelia:
        container_name: authelia
        <<: *common-settings
        image: *AUTHELIA
        networks:
            shared:
                ipv4_address: *AUTHELIA_IP
        secrets:
            - authelia_storage_encryption_key
            - authelia_jwt_secret
            - authelia_smtp_password
        environment:
            <<: *common-env
            X_AUTHELIA_CONFIG_FILTERS: template # Allows env var interpolation
            AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/authelia_storage_encryption_key
            AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /run/secrets/authelia_jwt_secret
            AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /run/secrets/authelia_smtp_password
            ##############
            ##   .env   ##
            ##############
            DOMAIN: ${DOMAIN}
        volumes:
            - /mnt/config/authelia:/config:z,rw

    ##############################
    ######      Caddy       ######
    ##############################
    caddy:
        container_name: caddy
        <<: *common-settings
        image: *CADDY
        networks:
            shared:
                ipv4_address: *CADDY_IP
        ports:
            - 8080:80
            - 4443:443
        environment:
            <<: [*common-env, *container-ips]
            ##############
            ##   .env   ##
            ##############
            DOMAIN: ${DOMAIN}
            ZEROSSL_EMAIL: ${ZEROSSL_EMAIL}
        volumes:
            - /mnt/config/caddy/Caddyfile:/etc/caddy/Caddyfile:z,ro
            - /mnt/config/caddy:/data/caddy:z,rw

    ##############################
    ######      Gickup      ######
    ##############################
    gickup:
        container_name: gickup
        <<: *common-settings
        image: *GICKUP
        networks:
            shared:
                ipv4_address: *GICKUP_IP
        volumes:
            - /mnt/bhulk/gickup:/data:rw
            - /mnt/config/gickup/conf.yml:/gickup/conf.yml:z,ro
        secrets:
            - gickup_vic1707_github_token

    ##############################
    ######     Jellyfin     ######
    ##############################
    jellyfin:
        container_name: jellyfin
        <<: *common-settings
        image: *JELLYFIN
        security_opt:
            - *no-privilege
            - label=disable
        networks:
            shared:
                ipv4_address: *JELLYFIN_IP
        environment:
            <<: *common-env
            # https://ffmpeg.org/ffmpeg-formats.html
            # probesize: 500000000 Bytes = 500 MB
            # analyzeduration: 60000000 Microseconds = 1 minute
            JELLYFIN_FFmpeg__probesize: 500000000
            JELLYFIN_FFmpeg__analyzeduration: 60000000
        volumes:
            - /mnt/config/jellyfin:/config:rw
            - /media/jellyfin:/media:ro
        devices:
            - nvidia.com/gpu=all

    ##############################
    ######   Transmission   ######
    ##############################
    transmission:
        container_name: transmission
        <<: *common-settings
        image: *TRANSMISSION
        privileged: true #  needed to acces /dev/net/tun
        networks:
            shared:
                ipv4_address: *TRANSMISSION_IP
        environment:
            <<: *common-env
            GLOBAL_APPLY_PERMISSIONS: false
            OPENVPN_CONFIG: netherlands
            OPENVPN_PROVIDER: PIA
            OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
            TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED: true
            TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME: /config/transmission-home/keep_torrent_file.sh
            TRANSMISSION_WEB_UI: flood-for-transmission
            WEBPROXY_ENABLED: false
            ## Wish I could remove ##
            CREATE_TUN_DEVICE: false
            DISABLE_PORT_UPDATER: true
        secrets:
            - openvpn_creds
        volumes:
            - /mnt/bhulk/transmission:/data:rw
            - /mnt/config/transmission:/config/transmission-home:z,rw
            - /mnt/config/transmission/keep_torrent_file.sh:/config/transmission-home/keep_torrent_file.sh:z
        devices: # wish I could remove
            - /dev/net/tun

    ##############################
    ######    Wireguard     ######
    ##############################
    wireguard:
        container_name: wireguard
        <<: *common-settings
        image: *WIREGUARD
        networks:
            shared:
                ipv4_address: *WIREGUARD_IP
        cap_add:
            - NET_ADMIN
            - NET_RAW
            - SYS_MODULE
        cap_drop:
            - MKNOD
            - AUDIT_WRITE
        environment:
            <<: *common-env
            WG_HOST: vpn.${DOMAIN}
            PASSWORD_HASH: ${WGUI_PASSWORD_HASH}
            WEBUI_HOST: *WIREGUARD_IP
            UI_TRAFFIC_STATS: true
            UI_ENABLE_SORT_CLIENTS: true
            UI_SHOW_LINKS: true
            UI_CHART_TYPE: 1
        volumes:
            - /mnt/config/wireguard:/etc/wireguard:z,rw
        ports:
            - 51820:51820/udp
        sysctls:
            net.ipv4.conf.all.src_valid_mark: 1
            net.ipv4.ip_forward: 1
            net.ipv6.conf.all.disable_ipv6: 1
