## TODO:
# Find a way for ansible to set the SSL/TLS Encryption mode to full
---
- name: Manage {{ domain }}
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    domain: vic1707.xyz
    cf_auth_token: "{{ lookup('community.general.passwordstore', 'domains/vic1707.xyz/api-key.cloudflare', subkey='key') }}"
    cf_account_name: vic1707

  vars_files:
    - dns-records/protonmail.ansible.yml
    - dns-records/brevo.ansible.yml
    - dns-records/homelab.ansible.yml

  tasks:
    - name: DNS records
      ansible.builtin.include_role:
        name: linuxhq.cloudflare.dns
      vars:
        cf_dns:
          - zone: "{{ domain }}"
            records: "{{
                protonmail_dns_records_map
                | combine(brevo_dns_records_map, list_merge='append')
                | combine(homelab_dns_records_map, list_merge='append')
                | moreati.jq.jq('to_entries | map(.value[] + { type: .key })')
              }}"
