---
## ansible-galaxy install -f -r .config/requirements.yml
collections:
  - name: community.general
    version: 11.1.2
  - name: linuxhq.cloudflare
    version: 1.2.0
  - name: moreati.jq
    version: 0.2.1
  - name: community.hrobot
    version: 2.5.0

roles:
  - name: rywillia.ssh-copy-id
