# TODO: fix volumes z options
# TODO: rm privileged transmission?
# TODO: execution capabilities on transmission config dir instead of just the script

networks:
    shared:
        name: shared
        driver: bridge
        ipam:
            config:
                - subnet: 10.99.0.0/26

############# GLOBAL VARIABLES ##############
x-TIMEZONE: &TIMEZONE Europe/Paris
##
x-CADDY: &CADDY docker.io/library/caddy:2.8.4-alpine
x-CADDY_IP: &CADDY_IP 10.99.0.2
##
x-GICKUP: &GICKUP docker.io/buddyspencer/gickup:0.10.31
x-GICKUP_IP: &GICKUP_IP 10.99.0.3
##
x-TRANSMISSION: &TRANSMISSION docker.io/haugene/transmission-openvpn:5.3.1
x-TRANSMISSION_IP: &TRANSMISSION_IP 10.99.0.4
##
x-JELLYFIN: &JELLYFIN docker.io/jellyfin/jellyfin:10.9.8
x-JELLYFIN_IP: &JELLYFIN_IP 10.99.0.5
##
x-WIREGUARD: &WIREGUARD ghcr.io/wg-easy/wg-easy:14
x-WIREGUARD_IP: &WIREGUARD_IP 10.99.0.6
########### GLOBAL CONFIGURATIONS ###########
x-ips: &container-ips
    CADDY_IP: *CADDY_IP
    GICKUP_IP: *GICKUP_IP
    JELLYFIN_IP: *JELLYFIN_IP
    TRANSMISSION_IP: *TRANSMISSION_IP

x-common-settings: &common-settings
    sysctls:
        - net.ipv6.conf.all.disable_ipv6=1
    security_opt:
        - &no-privilege no-new-privileges=true
    restart: always
    environment: &common-env
        TZ: *TIMEZONE
#############################################

services:
    ##############################
    ######      Caddy       ######
    ##############################
    caddy:
        container_name: caddy
        <<: *common-settings
        image: *CADDY
        networks:
            shared:
                ipv4_address: *CADDY_IP
        ports:
            - 8080:80
            - 4443:443
        environment:
            <<: [*common-env, *container-ips]
            ##############
            ##   .env   ##
            ##############
            DOMAIN: ${DOMAIN}
            ZEROSSL_EMAIL: ${ZEROSSL_EMAIL}
        volumes:
            - /mnt/config/caddy/Caddyfile:/etc/caddy/Caddyfile:z,ro
            - /mnt/config/caddy/data:/data:z,rw

    ##############################
    ######      Gickup      ######
    ##############################
    gickup:
        container_name: gickup
        <<: *common-settings
        image: *GICKUP
        networks:
            shared:
                ipv4_address: *GICKUP_IP
        volumes:
            - /mnt/bhulk/gickup/:/data:rw
            - /mnt/config/gickup:/config:z,ro
        command: /config/conf.yml

    ##############################
    ######     Jellyfin     ######
    ##############################
    jellyfin:
        container_name: jellyfin
        <<: *common-settings
        image: *JELLYFIN
        security_opt:
            - *no-privilege
            - label=disable
        networks:
            shared:
                ipv4_address: *JELLYFIN_IP
        environment:
            <<: *common-env
            # https://ffmpeg.org/ffmpeg-formats.html
            # probesize: 500000000 Bytes = 500 MB
            # analyzeduration: 60000000 Microseconds = 1 minute
            JELLYFIN_FFmpeg__probesize: 500000000
            JELLYFIN_FFmpeg__analyzeduration: 60000000
        volumes:
            - /mnt/config/jellyfin:/config:rw
            - /media/jellyfin:/media:ro
        devices:
            - nvidia.com/gpu=all

    ##############################
    ######   Transmission   ######
    ##############################
    transmission:
        container_name: transmission
        <<: *common-settings
        image: *TRANSMISSION
        privileged: true #  needed to acces /dev/net/tun
        networks:
            shared:
                ipv4_address: *TRANSMISSION_IP
        environment:
            <<: *common-env
            GLOBAL_APPLY_PERMISSIONS: false
            OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
            TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: true
            TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED: true
            TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME: /config/keep_torrent_file.sh
            TRANSMISSION_WEB_UI: flood-for-transmission
            WEBPROXY_ENABLED: false
            ## Wish I could remove ##
            CREATE_TUN_DEVICE: false
            DISABLE_PORT_UPDATER: true
            ##############
            ##   .env   ##
            ##############
            OPENVPN_CONFIG: ${OVPN_CONFIG}
            OPENVPN_PROVIDER: ${OVPN_PROVIDER}
            OPENVPN_USERNAME: ${OVPN_USR}
            OPENVPN_PASSWORD: ${OVPN_PWD}
            TRANSMISSION_RPC_USERNAME: ${TRANSMISSION_RPC_USERNAME}
            TRANSMISSION_RPC_PASSWORD: ${TRANSMISSION_RPC_PASSWORD}
        volumes:
            - /mnt/bhulk/transmission:/data:rw
            - /mnt/config/transmission:/config # because keep_torrent_file script
        devices: # wish I could remove
            - /dev/net/tun

    ##############################
    ######    Wireguard     ######
    ##############################
    wireguard:
        container_name: wireguard
        <<: *common-settings
        image: *WIREGUARD
        networks:
            shared:
                ipv4_address: *WIREGUARD_IP
        cap_add:
            - NET_ADMIN
            - NET_RAW
            - SYS_MODULE
        cap_drop:
            - MKNOD
            - AUDIT_WRITE
        environment:
            <<: *common-env
            WG_HOST: wg.${DOMAIN}
            PASSWORD_HASH: ${WGUI_PASSWORD_HASH}
            WEBUI_HOST: *WIREGUARD_IP # for setup : 0.0.0.0
            UI_TRAFFIC_STATS: true
            UI_ENABLE_SORT_CLIENTS: true
            UI_SHOW_LINKS: true
            UI_CHART_TYPE: 1
        volumes:
            - /mnt/config/wireguard:/etc/wireguard:z,rw
        ports:
            - 51820:51820/udp
            # for setup - 51821:51821/tcp
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
            - net.ipv4.ip_forward=1
            - net.ipv6.conf.all.disable_ipv6=1
