name: Draw.io-export

on:
  push:
    branches: [moving-out] # TODO: rename to main once we're done with big refacto
    paths:
      - "**.drawio"
      - .github/workflows/drawio-export.yml
  workflow_dispatch:

permissions:
  contents: write # <https://github.com/peaceiris/actions-gh-pages?tab=readme-ov-file#%EF%B8%8F-first-deployment-with-github_token>

jobs:
  drawio-export:
    name: drawio-export
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Use Draw.io CLI to export diagram
        uses: rlespinasse/drawio-export-action@v2.35.0
        with:
          format: svg
          remove-page-suffix: true

      - name: centralize exports
        run: |
          sudo mkdir exports
          sudo mv ./**/export/*.svg exports/

      - name: Push exported diagram to `diagrams` branch
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./exports
          publish_branch: diagrams
          force_orphan: true
