name: Ensure mise tools can be installed

on:
  push:
    branches:
      - main
    paths:
      - .mise.toml
      - requirements.txt
      - requirements.yml
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - .mise.toml
      - requirements.txt
      - requirements.yml
  workflow_dispatch:

permissions: {}

jobs:
  ensure-mise-tools:
    name: ensure-mise-tools
    runs-on: ubuntu-latest
    container:
      image: alpine@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11 # v3.22.1
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install asdf prerequisites
        run: apk add --no-cache curl git bash

      - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3

