name: Ensure mise tools can be installed

on:
  push:
    branches:
      - main
    paths:
      - .mise.toml
      - requirements.txt
      - requirements.yml
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - .mise.toml
      - requirements.txt
      - requirements.yml
  workflow_dispatch:

permissions: {}

jobs:
  ensure-mise-tools:
    name: ensure-mise-tools
    runs-on: ubuntu-latest
    container:
      image: alpine@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659 # v3.22.1
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install asdf prerequisites
        run: apk add --no-cache curl git bash

      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1

