name: Ensure mise tools can be installed

on:
  push:
    branches:
      - main
    paths:
      - .mise.toml
      - requirements.txt
      - requirements.yml
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - .mise.toml
      - requirements.txt
      - requirements.yml
  workflow_dispatch:

permissions: {}

jobs:
  ensure-mise-tools:
    name: ensure-mise-tools
    runs-on: ubuntu-latest
    container:
      image: alpine@sha256:4b7ce07002c69e8f3d704a9c5d6fd3053be500b7f1c69fc0d80990c2ad8dd412 # v3.22.1
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install asdf prerequisites
        run: apk add --no-cache curl git bash

      - uses: jdx/mise-action@9dc7d5dd454262207dea3ab5a06a3df6afc8ff26 # v3.4.1

