name: Ensure mise tools can be installed

on:
  push:
    branches:
      - main
    paths:
      - .mise.toml
      - requirements.txt
      - requirements.yml
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - .mise.toml
      - requirements.txt
      - requirements.yml
  workflow_dispatch:

permissions: {}

jobs:
  ensure-mise-tools:
    name: ensure-mise-tools
    runs-on: ubuntu-latest
    container:
      image: alpine@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1 # v3.22.1
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install asdf prerequisites
        run: apk add --no-cache curl git bash

      - uses: jdx/mise-action@ca0c5fc9c8a8386dae8ba5d37608a083a307991c # v3.1.0

