name: Lint & Format

on: [push, pull_request]

jobs:
  formatters:
    name: Beautysh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mfinelli/setup-shfmt@v3.0.1
      - run: shfmt -f -d -i 4 -s -ci -bn -sr .
      # fix command `shfmt -w -i 4 -s -ci -bn -sr .`

  linters:
    name: Shellcheck
    runs-on: ubuntu-latest
    needs: [formatters]
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck (no ZSH)
        uses: ludeeus/action-shellcheck@master
        env:
          # SC2034 is unused vars (triggered on .env files)
          SHELLCHECK_OPTS: -e SC2034 $(find . -type f -name '*.sh' -o -name '*.bash' -o -name '.env*')
