name: Lint & Format

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

permissions: {}

jobs:
  formatters:
    name: formatters
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1

      - name: shfmt
        # fix command `shfmt -w -i 4 -s -bn -ci -sr -kp .`
        run: |
          SUPPORTED_SHELLS="sh|bash"
          rg --ignore --hidden -l "^#!(.*/|.*env +)($SUPPORTED_SHELLS)" . \
              | xargs -r -t shfmt -d -i 4 -s -bn -ci -sr -kp

      - name: Caddy
        run: |
          find . \
            -type f -name "*Caddyfile" \
            -print \
            -execdir \
              podman run --rm -v .:/app --workdir /app caddy:latest caddy fmt {} +

  linters:
    name: linters
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      - name: Install python deps
        run: |
          pip install -r .config/requirements.txt
          echo PATH="${GITHUB_WORKSPACE}/.venv/bin:$PATH" >> "$GITHUB_ENV"

      - name: Shellcheck
        run: |
          SUPPORTED_SHELLS="sh|bash"
          rg --ignore --hidden -l "^#!(.*/|.*env +)($SUPPORTED_SHELLS)" . \
              | xargs -r -t shellcheck

      - name: Zizmor
        run: zizmor .
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Actionlint
        run: actionlint

      - name: Typos
        run: typos -c .config/.typos.toml

      - name: Ansible-lint
        run: ansible-lint -c .config/.ansible-lint.yml 

      - name: Butane
        run: |
          find . \
            -type f -name "*.bu.yml" \
            -print \
            -execdir \
              butane --strict --files-dir . --check {} +
