name: Lint & Format

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

permissions: {}

jobs:
  formatters:
    name: formatters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          persist-credentials: false
      - uses: jdx/mise-action@v3.0.2
      - name: Activate virtual environment
        run: echo PATH="${GITHUB_WORKSPACE}/.venv/bin:$PATH" >> "$GITHUB_ENV"

      - name: shfmt
        # fix command `shfmt -w -i 4 -s -bn -ci -sr -kp .`
        run: |
          SUPPORTED_SHELLS="sh|bash"
          rg -l "^#!(.*/|.*env +)($SUPPORTED_SHELLS)" . \
              | xargs -r -t shfmt -d -i 4 -s -bn -ci -sr -kp

      - name: Caddy
        run: |
          find . \
            -type f -name "*Caddyfile" \
            -print \
            -execdir \
              podman run --rm -v .:/app --workdir /app caddy:latest caddy fmt {} +

  linters:
    name: linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          persist-credentials: false
      - uses: jdx/mise-action@v3.0.2
      - name: Activate virtual environment
        run: echo PATH="${GITHUB_WORKSPACE}/.venv/bin:$PATH" >> "$GITHUB_ENV"

      - name: Shellcheck
        run: |
          SUPPORTED_SHELLS="sh|bash"
          rg -l "^#!(.*/|.*env +)($SUPPORTED_SHELLS)" . \
              | xargs -r -t shellcheck

      - name: Zizmor
        run: zizmor .
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Actionlint
        run: actionlint

      - name: Typos
        run: typos -c .config/.typos.toml

      - name: Ansible-lint
        run: ansible-lint -c .config/.ansible-lint.yml 

      - name: Butane
        run: |
          find . \
            -type f -name "*.bu.yml" \
            -print \
            -execdir \
              butane --strict --files-dir . --check {} +
