name: Lint & Format

on: [push, pull_request]

jobs:
  formatters:
    name: Beautysh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Beautysh
        uses: illvart/beautysh-action@latest
        with: # not in .git and not in ./shell/zsh/.zsh-plugins
          args: -c -i 2 -s paronly $(find . -not -path "./.git/*" \( -name "*.sh" -o -name "*.bash" -o -name "*.zsh" \))

  linters:
    name: Shellcheck
    runs-on: ubuntu-latest
    needs: [formatters]
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck (no ZSH)
        uses: ludeeus/action-shellcheck@master
        env:
          ## Work locally but not on CI ##
          # SC1090: Can't follow non-constant source.
          # SC1091: Not following.
          SHELLCHECK_OPTS: -e SC1090 -e SC1091
