name: Lint & Format

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

permissions: {}

jobs:
  formatters:
    name: formatters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
      - uses: jdx/mise-action@v2.2.1
      - name: Activate virtual environment
        run: echo PATH="${GITHUB_WORKSPACE}/.venv/bin:$PATH" >> "$GITHUB_ENV"

      - name: shfmt
        # fix command `shfmt -w -i 4 -s -ci -bn -sr .`
        run: shfmt -f -d -i 4 -s -ci -bn -sr .

  linters:
    name: linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
      - uses: jdx/mise-action@v2.2.1
      - name: Activate virtual environment
        run: echo PATH="${GITHUB_WORKSPACE}/.venv/bin:$PATH" >> "$GITHUB_ENV"

      - name: Shellcheck
        run: |
          SUPPORTED_SHELLS="sh|bash"
          rg -l "^#!(.*/|.*env +)($SUPPORTED_SHELLS)" . \
              | xargs -r -t shellcheck

      - name: Zizmor
        run: zizmor .
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Actionlint
        run: actionlint

      - name: Typos
        run: typos

      - name: Ansible-lint
        run: ansible-lint
